Add .editorconfig file to enforce editor rules
lnbook/lnbook pull request #141
Opened 2020-02-08 22:36 UTC by bolatovumar

2020-02-09 03:18 UTC, HAOYUatHZ commented
I am not sure whether an .editorconfig is desired.
not all the editors support .editorconfig natively, and it may require knowledge on such a tool.

I believe the travis lint check is enough?

2020-02-09 15:56 UTC, bolatovumar commented
@HAOYUatHZ I don't see why it wouldn't be desired. If your editor supports it then it will just use the config so you don't have to manually make changes like adding newlines at the end of every file for Travis build to pass. If your editor doesn't support it then you still lose nothing. There is nothing extra required from the user.

2020-02-09 16:23 UTC, aantonop commented
@bolatovumar Happy to merge this, but because you mixed edits and a new file in your PR, it now has conflicts. I suggest you separate PRs. In each PR do only one thing, in only one file. It's easier for the editors to merge smaller and more focused PRs that don't cause conflicts.

Can you split this into two PRs, or resolve the conflicts please?

2020-02-09 16:33 UTC, bolatovumar commented
@aantonop the reason I mixed in other stuff into this PR was because the build was failing prior to my PR and I really don't like submitting PRs which break the build so I had to fix up the build issues. I will rebase and resolve the conflicts.

2020-02-11 16:27 UTC, bolatovumar commented
@aantonop ping

2020-02-11 16:56 UTC, yahiheb requested changes

2020-02-11 16:56 UTC, yahiheb commented on 02_getting_started.asciidoc
> +Ofter the trust in those cases relates to privacy.
```suggestion
Often the trust in those cases relates to privacy.
```

2020-02-11 16:56 UTC, yahiheb commented on 02_getting_started.asciidoc
> +If users decides to outsource some functionality to a third party they usually give up some privacy as the third party will learn some information.
```suggestion
If users decide to outsource some functionality to a third party they usually give up some privacy as the third party will learn some information.
```

2020-02-11 21:06 UTC, bolatovumar commented
@yahiheb the changes you are suggesting are not related to this PR. This PR is specifically about adding an `.editorconfig` file to make it easier enforce certain rules and fixing up any issues that are currently breaking the build. You should open another PR which fixes the issues you pointed out.

2020-02-11 21:31 UTC, yahiheb commented
The typos were made in this PR https://github.com/lnbook/lnbook/pull/141/commits/9f54a72d05f3d633c8b64f95af0e3f06668923f9

2020-02-12 02:14 UTC, bolatovumar commented
@yahiheb ok, thanks, fixed now.

2020-02-12 17:02 UTC, merged

2020-02-12 17:03 UTC, aantonop commented
Thanks @bolatovumar !