Minor spelling and link edits
lnbook/lnbook pull request #54
Opened 2019-09-12 21:03 UTC by EAWF

2019-09-12 22:11 UTC, renepickhardt requested changes
the links don't appear inside the footnote. Would you please fix this? Otherwise thanks for the spelling mistakes.

2019-09-12 22:11 UTC, renepickhardt commented on ch01.asciidoc
> +During the first couple of years, the Bitcoin network was growing and the focus of many enthusiasts was on adoption, rather than the blocksize and scaling.  However, in 2012 Gavin Andresen proposed t
I am sorry but the `footnote:[]` commend in ascii doc does not work in this way. If you look how it renders the links are not in the clear text and not the footnote. I guess you would have to add link with a second pair of brackets inside the footnote

2019-09-13 01:55 UTC, EAWF commented on ch01.asciidoc
> +During the first couple of years, the Bitcoin network was growing and the focus of many enthusiasts was on adoption, rather than the blocksize and scaling.  However, in 2012 Gavin Andresen proposed t
Yes, My bad for not checking them out beforehand.  Sorry I wasn't able to get back online quickly. Thanks to whoever fixed them, they look awesome now.

2019-09-13 02:37 UTC, EAWF commented on ch01.asciidoc
> +During the first couple of years, the Bitcoin network was growing and the focus of many enthusiasts was on adoption, rather than the blocksize and scaling.  However, in 2012 Gavin Andresen proposed t
Nope, still not working.  My sincere apologies. I'm trying to figure out how to remove my pull request.  Not finding how to do it If you can delete the pull request, please go ahead and do it.

2019-09-13 02:37 UTC, closed without merging

2019-09-13 02:38 UTC, EAWF commented
I'll start over with the spelling errors, and found another grammatical error to do first.