Fix David => Dina
lnbook/lnbook pull request #636
Opened 2021-02-09 06:45 UTC by AndrejMitrovic

This follows the changes initially commited in 8abe629.

2021-02-09 07:32 UTC, AndrejMitrovic commented
I've added an additional commit fixing some more typos.

2021-02-11 19:18 UTC, GustavoRSSilva approved these changes

2021-03-23 15:53 UTC, renepickhardt requested changes
Thanks a lot! only change is about HMCA typo will fix that now and merge

2021-03-23 15:53 UTC, renepickhardt commented on routing.asciidoc
> +* The key exchanges of the sender might have been wrong so the decryption of the onion failed or the HMCAs do not match. (also in case someone tried to tamper with the onion)
just realized it should also be HMAC instead of HMCA will mege and fix afertwards

2021-03-23 15:57 UTC, merged