ch-07: technical edits to payment channels chapter
lnbook/lnbook pull request #740
Opened 2021-07-12 01:24 UTC by Roasbeef

A first pass of edits focused on technical accuracy through the current payment channels chapter. I've added a few important things not explicitly mentioned such as the existence of the upfront shutdown address, and the role of state hints during breach retribution. As usual, all edits are contained in individual commits so we can easily throw out certain edits or modify them.

2021-07-12 18:13 UTC, renepickhardt requested changes
We are still missing the part that the revocation key is basically only a partial key through linearity the homomorphism of going from private keys aka the elements in the additive group of Z/pZ to the Elliptic curve whose elements are the public keys. I think we really have to add that as I know it is confusing for many to have a revokation key when in reality it is only a partial key

2021-07-12 18:13 UTC, renepickhardt commented on 07_payment_channels.asciidoc
> +02a1cebfacb2674143b5ad0df3c22c609e935f7bc0ebe801f37b8e9023d45ea7b8
I am fine with having my public node id there it's connected to my identity anyway

2021-07-12 18:13 UTC, renepickhardt commented on 07_payment_channels.asciidoc
> +Note that in practice, the funding keys are deterministically _sorted_ (using lexicographical order of the serialized compressed form of the public keys) before being placed in the witness script (.
maybe as an info box? (but I think very useful to mention this!)

2021-07-16 12:23 UTC, merged

2021-07-22 02:39 UTC, Roasbeef commented
>  I think we really have to add that as I know it is confusing for many to have a revokation key when in reality it is only a partial key

Agreed, working on a follow up PR inspired by our conversation to explain why it would be insecure to just have a pubkey there that's 100% under control of the opposite party (they can just breach then take that path), then walk the reader through why the construction used today works in practice.