ch-07: construct revocation key derivation from first principles
lnbook/lnbook pull request #755
Opened 2021-07-23 02:00 UTC by Roasbeef

In this commit, we attempt to construct the derivation method we used to
derive the revocation keys from first principles. This explanation was
inspired by a conversation with Rene, leading to a sort of Socratic
method explanation w.r.t why the remote party cannot be allowed to
unilaterally sign with the revocation public key.

This initial draft explanation is a bit too technical IMO, but it's
unclear how much prior knowledge we can expect from the reader and/or
how much space we should devote for explaining this little trick.

One thing we may want to do is use some shorter variable names (defined
earlier) to make this section a bit more compact.

2021-07-23 06:31 UTC, renepickhardt requested changes
we don't write w book about group theory and ECDSA stuff but I have the feeling that this tip could be simplified heavily if we go a bit more on meta and extend the theory. I could give it a try because I think in the current version it is already more accessible than the BOLTs but still probably very technical. 

I would do something like explaining that: 
1. pubkey = privkey * G
2. (pub1 + pub2) = (priv_1 + priv_2) * G
3. (G can be any point in the group (it does not have to be the generator)
4. pub1 + pub2 is the point / address (revocation pub key) to which the comitment tx commits and can be derived from sharing pubkeys in channel setup
5. noone know priv1 + priv2 unless someone share the private key which is exactly how what happens

2021-07-23 06:31 UTC, renepickhardt commented on 07_payment_channels.asciidoc
> +In other words, the `revocationbase_priv` can only be derived (and used to sign for the `revocationpubkey` by the party that knows _both_ the `revocationbase_priv` _and_ the `per_commitment_secret`.
nit:  this little trick **IS** what makes ...

2021-08-18 01:46 UTC, Roasbeef commented
> I would do something like explaining that:

So we have a section that explains how ECDH works in the section on onion routing, IIRC that section goes after this section, but possibly we could place it here instead? 

Agree we don't want to go super into group theory, in my experience with developers new to this stuff, it's usually enough to show a long form expansion of the algebra, so they can see that everything reduces down to being able to do a public operation on that point, that can then be mirrored on the private data to derive the new key.

2021-08-18 01:52 UTC, Roasbeef commented
Rebased and fixed the typo.

2021-09-17 01:57 UTC, merged